title: Your awesome title
author: Sarah Sophia
email: safiralaviera@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  in this blog, I pretend to share my learning process through github and code.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  Sarah-Sophia # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
